version: '3.4'

services:
  webapicore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webappcorewithapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

