version: '3.4'

services:
  webapicore:
    image: ${DOCKER_REGISTRY-}webapicore
    build:
      context: .
      dockerfile: WebApiCore\Dockerfile

  webappcorewithapi:
    image: ${DOCKER_REGISTRY-}webappcorewithapi
    build:
      context: .
      dockerfile: WebAppCoreWithApi\Dockerfile

