version: '3.4'

services:
  webapicore:
    image: webapicore:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapicore$
    volumes:
      - C:\Users\sijox\Desktop\Testapps-containerization\WebAppCoreWithApi\WebApiCore:C:\app
      - C:\Users\sijox\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_webapicore$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapicore$ bin\\Debug\\netcoreapp2.1\\WebApiCore.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

  webappcorewithapi:
    image: webappcorewithapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webappcorewithapi$
    volumes:
      - C:\Users\sijox\Desktop\Testapps-containerization\WebAppCoreWithApi\WebAppCoreWithApi:C:\app
      - C:\Users\sijox\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_webappcorewithapi$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webappcorewithapi$ bin\\Debug\\netcoreapp2.1\\WebAppCoreWithApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

