version: '3.4'

services:
  eshoplegacymvc:
    image: eshoplegacymvc:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\sijox\Desktop\Testapps-containerization\eShopLegacyMVCSolution\src\eShopLegacyMVC:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800


  eshopwebapi:
    image: eshopwebapi:dev
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - C:\Users\sijox\Desktop\Testapps-containerization\eShopLegacyMVCSolution\eShopWebAPI:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800


