version: '3.4'

services:
  eshoplegacymvc:
    build:
      args:
        source: obj/Docker/publish/
    volumes:
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\eShopLegacyMVC.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"

  eshopwebapi:
    build:
      args:
        source: obj/Docker/publish/
    volumes:
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\eShopWebAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"

